name: Production CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: Create deployment package
        run: |
          cd backend
          mkdir -p .platform/hooks/prebuild
          cat > .platform/hooks/prebuild/01_install_node.sh << 'EOL'
          #!/bin/bash
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20
          nvm alias default 20
          echo "Node.js version set to: $(node -v)"
          EOL
          chmod +x .platform/hooks/prebuild/01_install_node.sh
          zip -r deploy.zip . -x "node_modules/*" "*.git*" "*.env*" "postman/*" "*.md" "dist/*" "netlify/*" "scripts/*"
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Propease-Backend-2
          environment_name: Propease-Backend-2-env
          version_label: prod-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          region: us-east-2
          deployment_package: backend/deploy.zip
          wait_for_environment_recovery: 300
          use_existing_version_if_available: true

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Inform User About Deployment
        run: |
          echo "Frontend build completed!"
          echo "Please deploy manually from the AWS Amplify Console"
          echo "The frontend code has been built and is ready for deployment" 